// 这个文件供CI脚本使用，别乱动,动一个字符都要咨询后台开发
#ifndef DOBOTLINK_VERSION_H
#define DOBOTLINK_VERSION_H

#define VERSION_MAIN "5.13.1"
#define VERSION_PLUGIN_MAGICDEVICE "3.4.4"
#define VERSION_PLUGIN_INDUSTRIAL "1.1.0"
#define VERSION_PLUGIN_ARDUINO "1.0.0"
#define VERSION_PLUGIN_DEBUGGER "1.3.3"
#define VERSION_PLUGIN_DEBUGGERLITE "1.0.0"
#define VERSION_PLUGIN_DOWNLOAD "1.0.0"
#define VERSION_PLUGIN_DYNAMIC "1.1.1"
#define VERSION_PLUGIN_IMAGE "1.1.2"
#define VERSION_PLUGIN_CODING "1.0.0"
#define VERSION_PLUGIN_RUNCMD "1.0.0"

#endif // DOBOTLINK_VERSION_H
